COMPONENT_ADD_INCLUDEDIRS := src
COMPONENT_SRCDIRS := src

CXXFLAGS += -DESPRESSIO_STATE
CXXFLAGS += -DESPRESSIO_STATE_VERSION_MAJOR=0
CXXFLAGS += -DESPRESSIO_STATE_VERSION_MINOR=1
CXXFLAGS += -DESPRESSIO_STATE_VERSION_PATCH=0
CXXFLAGS += -DESPRESSIO_STATE_VERSION_STRING=\"0.1.0\"
CXXFLAGS += -std=gnu++17
